# coding: utf-8

"""
    Network Perspective

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: ext-v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class AggregateEnum(str, Enum):
    """
    AggregateEnum
    """

    """
    allowed enum values
    """
    MONTH = 'Month'
    WEEKDAY = 'Weekday'
    HOUR = 'Hour'
    CUSTOM = 'Custom'
    SANDBOX = 'Sandbox'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AggregateEnum from a JSON string"""
        return cls(json.loads(json_str))


