# coding: utf-8

"""
    Network Perspective

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: ext-v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from np_client.models.hashed_entity_relationship import HashedEntityRelationship
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class HashedEntity(BaseModel):
    """
    HashedEntity
    """ # noqa: E501
    change_date: Optional[datetime] = Field(default=None, alias="changeDate")
    ids: Optional[Dict[str, StrictStr]] = None
    groups: Optional[List[StrictStr]] = None
    props: Optional[Dict[str, Any]] = None
    relationships: Optional[List[HashedEntityRelationship]] = None
    __properties: ClassVar[List[str]] = ["changeDate", "ids", "groups", "props", "relationships"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HashedEntity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in relationships (list)
        _items = []
        if self.relationships:
            for _item in self.relationships:
                if _item:
                    _items.append(_item.to_dict())
            _dict['relationships'] = _items
        # set to None if change_date (nullable) is None
        # and model_fields_set contains the field
        if self.change_date is None and "change_date" in self.model_fields_set:
            _dict['changeDate'] = None

        # set to None if ids (nullable) is None
        # and model_fields_set contains the field
        if self.ids is None and "ids" in self.model_fields_set:
            _dict['ids'] = None

        # set to None if groups (nullable) is None
        # and model_fields_set contains the field
        if self.groups is None and "groups" in self.model_fields_set:
            _dict['groups'] = None

        # set to None if props (nullable) is None
        # and model_fields_set contains the field
        if self.props is None and "props" in self.model_fields_set:
            _dict['props'] = None

        # set to None if relationships (nullable) is None
        # and model_fields_set contains the field
        if self.relationships is None and "relationships" in self.model_fields_set:
            _dict['relationships'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of HashedEntity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "changeDate": obj.get("changeDate"),
            "ids": obj.get("ids"),
            "groups": obj.get("groups"),
            "props": obj.get("props"),
            "relationships": [HashedEntityRelationship.from_dict(_item) for _item in obj.get("relationships")] if obj.get("relationships") is not None else None
        })
        return _obj


