# coding: utf-8

"""
    Network Perspective

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: ext-v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class HashedInteractionLabel(str, Enum):
    """
    HashedInteractionLabel
    """

    """
    allowed enum values
    """
    CHAT = 'Chat'
    EMAIL = 'Email'
    MEETING = 'Meeting'
    NEWTHREAD = 'NewThread'
    REPLY = 'Reply'
    REACTION = 'Reaction'
    RECURRINGDAILY = 'RecurringDaily'
    RECURRINGWEEKLY = 'RecurringWeekly'
    RECURRINGMONTHLY = 'RecurringMonthly'
    RECURRINGYEARLY = 'RecurringYearly'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HashedInteractionLabel from a JSON string"""
        return cls(json.loads(json_str))


