# coding: utf-8

"""
    Network Perspective

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: ext-v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from np_client.models.aggregate_enum import AggregateEnum

class TestAggregateEnum(unittest.TestCase):
    """AggregateEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAggregateEnum(self):
        """Test AggregateEnum"""
        # inst = AggregateEnum()

if __name__ == '__main__':
    unittest.main()
