# coding: utf-8

"""
    Network Perspective

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: ext-v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from np_client.models.sync_users_command import SyncUsersCommand

class TestSyncUsersCommand(unittest.TestCase):
    """SyncUsersCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncUsersCommand:
        """Test SyncUsersCommand
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncUsersCommand`
        """
        model = SyncUsersCommand()
        if include_optional:
            return SyncUsersCommand(
                service_token = '',
                users = [
                    np_client.models.user_entity.UserEntity(
                        email = '', 
                        ids = {
                            'key' : ''
                            }, 
                        props = {
                            'key' : null
                            }, 
                        group_access = [
                            ''
                            ], )
                    ],
                instant = True
            )
        else:
            return SyncUsersCommand(
        )
        """

    def testSyncUsersCommand(self):
        """Test SyncUsersCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
