# coding: utf-8

"""
    Network Perspective

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: ext-v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from np_client.models.token_response_model import TokenResponseModel

class TestTokenResponseModel(unittest.TestCase):
    """TokenResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenResponseModel:
        """Test TokenResponseModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokenResponseModel`
        """
        model = TokenResponseModel()
        if include_optional:
            return TokenResponseModel(
                access_token = '',
                token_type = '',
                expires_in = 56,
                refresh_token = '',
                issued = '',
                expires = '',
                asclient_id = '',
                user_name = ''
            )
        else:
            return TokenResponseModel(
        )
        """

    def testTokenResponseModel(self):
        """Test TokenResponseModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
