# coding: utf-8

"""
    Network Perspective

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: ext-v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from np_client.api.sync_hashed_api import SyncHashedApi


class TestSyncHashedApi(unittest.TestCase):
    """SyncHashedApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SyncHashedApi()

    def tearDown(self) -> None:
        pass

    def test_sync_hashed_query(self) -> None:
        """Test case for sync_hashed_query

        Validate service token
        """
        pass

    def test_sync_hashed_report_completed(self) -> None:
        """Test case for sync_hashed_report_completed

        Sync completed
        """
        pass

    def test_sync_hashed_report_start(self) -> None:
        """Test case for sync_hashed_report_start

        Sync started
        """
        pass

    def test_sync_hashed_settings(self) -> None:
        """Test case for sync_hashed_settings

        Settings
        """
        pass

    def test_sync_hashed_sync_entities(self) -> None:
        """Test case for sync_hashed_sync_entities

        Sync entities
        """
        pass

    def test_sync_hashed_sync_groups(self) -> None:
        """Test case for sync_hashed_sync_groups

        Sync groups
        """
        pass

    def test_sync_hashed_sync_interactions(self) -> None:
        """Test case for sync_hashed_sync_interactions

        Sync interactions
        """
        pass

    def test_sync_hashed_sync_users(self) -> None:
        """Test case for sync_hashed_sync_users

        Sync users
        """
        pass


if __name__ == '__main__':
    unittest.main()
