# coding: utf-8

"""
    Network Perspective

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: ext-v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from np_client.models.hashed_interaction_label import HashedInteractionLabel

class TestHashedInteractionLabel(unittest.TestCase):
    """HashedInteractionLabel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHashedInteractionLabel(self):
        """Test HashedInteractionLabel"""
        # inst = HashedInteractionLabel()

if __name__ == '__main__':
    unittest.main()
