# coding: utf-8

"""
    Network Perspective

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: ext-v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from np_client.models.sync_hashed_group_structure_command import SyncHashedGroupStructureCommand

class TestSyncHashedGroupStructureCommand(unittest.TestCase):
    """SyncHashedGroupStructureCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncHashedGroupStructureCommand:
        """Test SyncHashedGroupStructureCommand
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncHashedGroupStructureCommand`
        """
        model = SyncHashedGroupStructureCommand()
        if include_optional:
            return SyncHashedGroupStructureCommand(
                service_token = '',
                groups = [
                    np_client.models.hashed_group.HashedGroup(
                        id = '', 
                        client_group_id = '', 
                        name = '', 
                        category = '', 
                        parent_id = '', )
                    ]
            )
        else:
            return SyncHashedGroupStructureCommand(
        )
        """

    def testSyncHashedGroupStructureCommand(self):
        """Test SyncHashedGroupStructureCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
