# coding: utf-8

"""
    Network Perspective

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: ext-v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from np_client.api.token_api import TokenApi


class TestTokenApi(unittest.TestCase):
    """TokenApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TokenApi()

    def tearDown(self) -> None:
        pass

    def test_token_get_token(self) -> None:
        """Test case for token_get_token

        Issue an access token
        """
        pass


if __name__ == '__main__':
    unittest.main()
