# coding: utf-8

"""
    Network Perspective

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: ext-v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from np_client.models.user_entity import UserEntity

class TestUserEntity(unittest.TestCase):
    """UserEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserEntity:
        """Test UserEntity
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserEntity`
        """
        model = UserEntity()
        if include_optional:
            return UserEntity(
                email = '',
                ids = {
                    'key' : ''
                    },
                props = {
                    'key' : null
                    },
                group_access = [
                    ''
                    ]
            )
        else:
            return UserEntity(
        )
        """

    def testUserEntity(self):
        """Test UserEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
